### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by x0sky** [rokudev/automated-channel-testing#5]
I get the following error when I run this command, could somebody please tell me where I am going wrong? Thank you

**python3 /Users/aad64/Downloads/automated-channel-testing-master/sample/script/main.py**

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10f829040>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /v1/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f829040>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aad64/Downloads/automated-channel-testing-master/sample/script/main.py", line 19, in <module>
    web_driver = WebDriver("10.189.174.14")
  File "/Users/aad64/Downloads/automated-channel-testing-master/sample/script/webDriver.py", line 25, in __init__
    response = self._post(request_url, data)
  File "/Users/aad64/Downloads/automated-channel-testing-master/sample/script/webDriver.py", line 56, in _post
    return requests.post(url = request_url, data = json.dumps(data))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /v1/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f829040>: Failed to establish a new connection: [Errno 61] Connection refused'))
macbook-pro:~ aad64$

**Comment by andrii-kovtko** [comment]
Hello @x0sky ,
Did you start instance of Roku  webDriver ?  You should do steps 1-6 from README.md.
Thank you.

**Comment by TimB0** [comment]
> Hello @x0sky ,
> Did you start instance of Roku webDriver ? You should do steps 1-6 from README.md.
> Thank you.

Hello @andrii-kovtko 

Looks like those steps were removed from the README file.  Im looking at the history of the file and their were instructions on setting up and running a GO server.  Those instructions are no longer in the latest version of the README.  Could those be put back in?

I will perform the steps i see in the previous version and see if it fixes this bug.

**Comment by TimB0** [comment]
i found the problem...you have to start one of the RokuWebDriver servers in the bin directory before you run your test.  I will create a pull request to update the README then close this
@andrii-kovtko @x0sky

**Comment by batmazhan** [comment]
Hi, I do get still same issue, would you share the exact steps for the fix? thanks
